baseurl = "https://tellme.tokyo"
languageCode = "ja-jp"
title = "tellme.tokyo"
copyright = "BABAROT All Right Reserved."
googleAnalytics = "UA-44183504-2"
publishDir = "docs"

pygmentsUseClasses = true
pygmentsCodefences = true

# default is 10
paginate = 10

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Masaki ISHIYAMA"
keywords = ["b4b4r07", "babarot"]
author = "b4b4r07"
profile = "profile.jpg"
website = "https://b4b4r07.github.io"
sharingicons = true
displayauthor = false
displayoldlink = true
readmore = false
avatar = "https://raw.githubusercontent.com/b4b4r07/tellme.tokyo/master/static/images/profile.jpg"

# [params.permalinks]
# post = "/post/:year/:month/:day/:filename/"

[permalinks]
  post = "/post/:year/:month/:day/:filename/"

[params.sharing]
twitter = true
hatebu = true
pocket = false

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/b4b4r07"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/b4b4r07"
fa_icon = "fa-twitter"

[outputFormats]
  [outputFormats.RSS]
    baseName = "feed"
